on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: vishal.azurecr.io
        username: ${{ secrets.acr_vishal_username }}
        password: ${{ secrets.acr_vishal_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/Application" -f  "Application/Dockerfile" -t vishal.azurecr.io/vijainaks:${{ github.sha }}
        docker push vishal.azurecr.io/vijainaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_vijainaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep vijainaksba42 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace vijainaksba42`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: vijainaksba42
        container-registry-url: vishal.azurecr.io
        container-registry-username: ${{ secrets.acr_vishal_username }}
        container-registry-password: ${{ secrets.acr_vishal_password }}
        secret-name: vijainaksdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: vijainaksba42
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          vishal.azurecr.io/vijainaks:${{ github.sha }}
        imagepullsecrets: |
          vijainaksdockerauth